### ISSUE TITLE
Request for Dockerfile

### ISSUE THREAD

**Issue by SauravMaheshkar** [larskuenkel/DeepPulsarNet#2]
Hey @larskuenkel, I was going through your repository and tried to set them up working on a Linux VM. But honestly installing `sigpyproc`, `Tempo2` and `SKA-TestVectorGenerationPipeline` is very frustrating. It'd be much easier if there was a `Dockerfile`  provided. That would make reproducibility and benchmarking much easier.

**Comment by larskuenkel** [comment]
Hey @SauravMaheshkar, thanks for the interest in the repository. I agree that installing the needed software can be very frustrating. I will have a look if I can supply a usable Dockerfile.

**Comment by SauravMaheshkar** [comment]
@larskuenkel based on the `Dockerfile` provided in the `SKA-TestVectorGenerationPipeline` repository I modified it a bit to support PyTorch with a few extensions. The full size of the image is **7.49GB**. Maybe this could work ??

If this sounds good, what do you think are the next steps to get it tested ?

**Comment by larskuenkel** [comment]
Adapting that Dockerfile from that repository sounds like a good idea. I used v1.0 of `SKA-TestVectorGenerationPipeline` because he changed things around later which made it less convenient for my purposes. So ones would have to grab the v1.0 release or the v1.1 branch.

Following the steps in the `README.md` are a good next step, so downloading the example observations I put there and creating some simulated pulsars. I used the notebooks to create my simulated data and so one might rework those into scripts if one prefers to work with those.

I can have a look if the Dockerfile works for me or whats needs to be changed but I will only be able to do so in the new year.

**Comment by SauravMaheshkar** [comment]
@larskuenkel Sounds good. Do you think I should also add support for Jupyter Notebooks ? As in instead of connecting to a bash terminal maybe the docker image would just open a Jupyter notebook environment with the data already installed ?? That way running and reproducing the experiments would be as simple as just executing cells ?

**Comment by larskuenkel** [comment]
I only did use notebooks for the data creation and the (optional) visual inspection. Since depending on the setup using notebooks may be less accessible than using command line commands I think doing it via the notebooks may not be easiest thing. Curently I think for the data creation one has to adapt the existing notebook by entering the path to the `SKA-TestVectorGenerationPipeline` and point it towards a filterbank file that wil be used as template for the observations.

I suspect converting the notebooks to scripts that can be executed after the the Docker has been opened and those download the real files and create simulated files should be the most convenient.

**Comment by SauravMaheshkar** [comment]
@larskuenkel any thoughts on the `Dockerfile` ?

**Comment by larskuenkel** [comment]
Hey, I a first look at the docker file. I am not very well versed with docker files so this is taking a while.
For me with your file it fails building because of `RUN pip3 install --no-cache-dir --update wheel pip` where it does not know `--update`. Did you mean -`-upgrade`? With that change it built successfully but I have not tried using it.

It might be a good idea to use the `Dockerfile` from Presto as a base since that is useful for further analysis anyway: https://github.com/scottransom/presto/blob/master/Dockerfile
I will have a go at adding the `sigproc` install and my version of `SKA-TestVectorGenerationPipeline` to their Dockerfile and see if I can make an easily executable tutorial on Tuesday most likely.

(One thing to note is that the original version of the `SKA-TestVectorGenerationPipeline` that I use for my purposes is not Python3 compatible so I used my fork at https://github.com/larskuenkel/SKA-TestVectorGenerationPipeline ).

Edit: I created a new branch `add_docker` that contains a Dockerfile based on your Dockerfile and the presto Dockerfile. Currently no presto is installed since there is an error. On Tuesday I will test if I can write a tutorial using that Dockerfile.

**Comment by SauravMaheshkar** [comment]
Hey @larskuenkel 👋  were you able to spin something up ?

**Comment by larskuenkel** [comment]
Ah yes. I moved the creation to another Python library and now you only really need to install the Python dependencies. I think in the current version there is also a simple Dockerfile which might work but I think I can remove parts of it.

You can test by performing the tutorial as outlined in the Readme.

**Comment by SauravMaheshkar** [comment]
Thanks this look way cleaner and slick now. Although there's a slight correction to the `README.md`, in the Tutorial section the 3rd script is bash and not python.

**Comment by SauravMaheshkar** [comment]
Added the mentioned changes in #5

**Comment by SauravMaheshkar** [comment]
Closing the issue as it's resolved.
